# Generated by Django 5.0.1 on 2024-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("assignee", models.CharField(max_length=200)),
                ("assignment", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Complete", "Complete"),
                            ("Delayed", "Delayed"),
                            ("Cancelled", "Cancelled"),
                            ("Incomplete", "Incomplete"),
                        ],
                        default="Pending",
                        max_length=200,
                    ),
                ),
                (
                    "primary_cause",
                    models.CharField(
                        choices=[
                            ("Manpower", "Manpower"),
                            ("Process(es)", "Process(es)"),
                            ("Money", "Money"),
                            ("Machinery", "Machinery"),
                            ("Matrices", "Matrices"),
                            ("Culture", "Culture"),
                        ],
                        default="Process(es)",
                        max_length=200,
                    ),
                ),
                ("problem", models.CharField(max_length=255)),
                ("why1", models.CharField(max_length=255)),
                ("why2", models.CharField(max_length=255)),
                ("why3", models.CharField(max_length=255)),
                ("why4", models.CharField(max_length=255)),
                ("root_cause", models.CharField(max_length=255)),
            ],
        ),
    ]
