# Generated by Django 5.0.1 on 2024-02-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="primary_cause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manpower", "Manpower"),
                    ("Process(es)", "Process(es)"),
                    ("Money", "Money"),
                    ("Machinery", "Machinery"),
                    ("Matrices", "Matrices"),
                    ("Culture", "Culture"),
                ],
                default="Process(es)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="problem",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="root_cause",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="why1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="why2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="why3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="why4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
